# Generated by Django 3.1.4 on 2021-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210111_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestate',
            name='EMPstate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeestate',
            name='RoomID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
