# Generated by Django 3.1.4 on 2021-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210124_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='imagesettings',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/pics/'),
        ),
    ]
